export const techList = [
  'JavaScript (ES6+)',
  'TypeScript',
  'Node. js',
  'Express',
  'Docker',
  'NGINX',
  'Next js',
  'REACT ',
  'Jest js',
  'GraphQL',
  'PHP',
  'Laravel 7',
  'MongoDB',
  'SQL(Postgresql, Mysql)',
  'Data mining(Puppeteer , NightmareJS)',
  'HTML & (S)CSS',
]
